### ISSUE TITLE
Unable to install MMPBSA.py.MPI

### ISSUE THREAD

**Issue by darkwhite29** [2019-ncovgroup/DrugWorkflows#13]
I installed AmberTools on Summit following the procedures: https://github.com/2019-ncovgroup/DrugWorkflows/tree/devel/workflow-3, but cannot see MMPBSA.py.MPI in the bin directory (MMPBSA.py is there).

Hyungro, could you please confirm it is the case for you as well on Summit?

**Comment by lee212** [comment]
No I haven’t installed amber19, can’t say what this problem is.

**Comment by darkwhite29** [comment]
Do you think you have time to go through the installation steps to see if you can have MMPBSA.py.MPI installed? I just need to confirm with you if I did anything wrong.

**Comment by lee212** [comment]
Not a problem, let me try.

**Comment by darkwhite29** [comment]
Thanks a lot. Take your time.

**Comment by darkwhite29** [comment]
Hyungro, I have pulled the EnTK script you updated, and made some changes to make it work. However, I don't have push access to this repository so I cannot push my changes to Github. Would you add me the push access?

Also, if you finish installing AmberTools and find MMPBSA.py.MPI in the bin, please let me know. Thanks!

**Comment by shantenujha** [comment]
Hi @darkwhite29  -- You have a pending invitation to write to the Git repo. Please accept the invite or if you can't find the invite, please let me know and I'll send you a fresh invite.

**Comment by darkwhite29** [comment]
I did not see the invitation. Thanks.

**Comment by shantenujha** [comment]
I re-sent an invite to darkwhite29

**Comment by darkwhite29** [comment]
I received and accepted it. Thanks!

**Comment by shantenujha** [comment]
Great. You should be able to commit now ..

**Comment by lee212** [comment]
@darkwhite29 , have you tried conda for mpi4py installation? like:
```
conda install mpi4py -y
```

I applied this to the [README](https://github.com/2019-ncovgroup/DrugWorkflows/blob/devel/workflow-3/README.md), and I hope this allows to have the mpi version of mmpbsa, i.e. `MMPBSA.py.MPI`.

**Comment by darkwhite29** [comment]
mpi4py is part of the AmberTools which needs to be built during the AmberTools compilation. Installing mpi4py separately does not prevent building mpi4py inside AmberTools. Thanks for the insight though. I managed to make it work, and I am closing this ticket.

The solution that works for me: using miniconda python2.7 during AmberTools configuration and module load gcc/7.4.0

**Comment by mturilli** [comment]
@darkwhite29 , are you sure we should use python 2.7?

**Comment by darkwhite29** [comment]
python 2.7 is the suggested python version by Agastya to run this workflow @apbhati1 @lee212

**Comment by lee212** [comment]
@darkwhite29 , I think you can use py3, ambertools support python3.4.x or higher.

**Comment by darkwhite29** [comment]
I tested and found it runs OK with py3. Thanks @lee212 @mturilli
