### ISSUE TITLE
Error when running the last stage of workflow 2

### ISSUE THREAD

**Issue by atrifan2** [2019-ncovgroup/DrugWorkflows#14]
![20200401_111540](https://user-images.githubusercontent.com/31902227/78168435-8dc73780-7415-11ea-9c0e-7434144d82ad.jpg)

I get this error printing all the time in the window I am running on Summit, but no errors in the sandbox STDERR or STDOUT. Sorry about the picture, i cannot copy any of this output while it is printing.

**Comment by lee212** [comment]
@andre-merzky , I am not sure what this is about, but you might have some clue?

**Comment by lee212** [comment]
@mturilli and others, the sandbox for this is at 
`/gpfs/alpine/proj-shared/med110/entk_error_logs/re.session.login1.atrifan2.018353.0002`
and the script executed is at:
`/gpfs/alpine/proj-shared/med110/entk_error_logs/entk_cvae_md/summit_md.py`

**Comment by andre-merzky** [comment]
@lee212 , @atrifan2 : thanks for the ping, let me take a look.

**Comment by andre-merzky** [comment]
@lee212 : this is likely related to radical-cybertools/radical.pilot/pull/2111.  If so, it will require a merge on RU, RS and RP to permanently fix - until then we'll have to clean out the client processes manually from time to time.

@atrifan2 : Can you please do the following:
```
$ ps -f -u atrifan2 | grep -v grep | grep rp.pmgr_launching.0000 | cut -c 9-15 | xargs kill
```
You also seems to have on instance of the code still running - please interrupt it before doing the above.  Then please wait 2 minutes for some timeouts to kick in to clear the remaining processes, and then run again.  Please report if you observe the same behavior still.

Apologies for that problem, it caught us very unexpectedly in a part of the code we considered very stable...

**Comment by atrifan2** [comment]
@andre-merzky I executed the command. Thank you for your help

**Comment by lee212** [comment]
The latest release would resolve this and the pip upgrade is:
```
pip install --upgrade radical.pilot radical.utils radical.saga
```

I believe this can be closed.
