### ISSUE TITLE
Still getting runs killed 

### ISSUE THREAD

**Issue by atrifan2** [2019-ncovgroup/DrugWorkflows#16]
Hi,

I am still having issues running workflow 2 on Summit. I am now trying to run 2 different proteins and it seems like they are killed randomly. I killed all stale processes before starting these runs. One of them stopped before the CVAE stage and the other before the outlier search stage.  The path to the radical sandbox is 

/gpfs/alpine/scratch/atrifan2/med110/radical.pilot.sandbox

Please let me know how to proceed. 

Anda

**Comment by lee212** [comment]
I am afraid that I have access to your scratch directory. Can you copy those two sessions to `$PROJWORK/med110/entk_error_logs`?

I will take a look further but I wonder if you ran two proteins at the same time? wf-2 is dependent on files and the launched location needs to be separated to working properly. 

I will update once I find out something.

**Comment by andre-merzky** [comment]
Alas, I can't access the sandbox:
```sh
$ cd /gpfs/alpine/med110/scratch/atrifan2
-bash: cd: /gpfs/alpine/med110/scratch/atrifan2: Permission denied
```
Would you mind opening the permissions?  I _think_ the following should do the trick:

```sh
$ chmod g+rX /gpfs/alpine/med110/scratch/atrifan2
$ chmod -R g+rX /gpfs/alpine/med110/scratch/atrifan2/radical.pilot.sandbox
```

**Comment by lee212** [comment]
We've been discussed to resolve the early termination issue by some tricks like persistent terminal sessions with tmux/screen/nohup and we will wait/see if it happens again. But, for the record, what we found for the failures of these two runs, units were terminated with the message:
```
Could not read jskill result from pmix server
```
and the bhist tells `SIGINT` was raised:
```
Fri Apr 10 08:40:35: Starting (Pid 129548);
Fri Apr 10 08:40:49: Running with execution home </ccs/home/atrifan2>, Executio
                     n CWD </gpfs/alpine/scratch/atrifan2/med110/radical.pilot.
                     sandbox/re.session.login4.atrifan2.018361.0004/pilot.0000>
                     , Execution Pid <129548>;
Fri Apr 10 08:40:49: CSM_ALLOCATION_ID=1036373;
Fri Apr 10 22:03:03: Signal <KILL> requested by user or administrator <atrifan2
                     >;
Fri Apr 10 22:04:09: Exited with exit code 130. The CPU time used is 0.0 second
                     s;
Fri Apr 10 22:04:09: Completed <exit>; TERM_OWNER: job killed by owner;
3:34
```
and 
```
Fri Apr 10 08:40:35: Starting (Pid 129551);
Fri Apr 10 08:40:49: Running with execution home </ccs/home/atrifan2>, Executio
                     n CWD </gpfs/alpine/scratch/atrifan2/med110/radical.pilot.
                     sandbox/re.session.login5.atrifan2.018361.0005/pilot.0000>
                     , Execution Pid <129551>;
Fri Apr 10 08:40:49: CSM_ALLOCATION_ID=1036374;
Fri Apr 10 21:18:02: Signal <KILL> requested by user or administrator <atrifan2
                     >;
Fri Apr 10 21:19:15: Exited with exit code 130. The CPU time used is 0.0 second
                     s;
Fri Apr 10 21:19:15: Completed <exit>; TERM_OWNER: job killed by owner;
```

**Comment by andre-merzky** [comment]
@lee212 : thanks for the update.  Is that problem reproducible for you, or specific to @atrifan2's environment?  Either way, can either of you please provide a client and a pilot sandbox created with `export RADICAL_LOG_LVL=DEBUG` set?  Thank you.

**Comment by lee212** [comment]
Since this is not reproducible, I propose to close for the moment.
