### ISSUE TITLE
[WF2/Longhorn] tf is hang?

### ISSUE THREAD

**Issue by lee212** [2019-ncovgroup/DrugWorkflows#19]
@mtitov , 

I waited enough time to see some outputs of CVAE but it doesn't seem working? there is no STDERR/STDOUT. Could you check if this stage has a hanging problem with keras/tf2/cuda10?

I pushed the `longhorn.py` script and generate_aggregating_stage() is the stage I couldn't get trained models. BTW, other stages seem fine, OpenMM and hdf5 conversion.

The bash shell looks like, for example:
```
export OMP_NUM_THREADS="4"
export "CUDA_VISIBLE_DEVICES=0"

...

mpirun  -np 1  -host c001-005 -envlist "LD_LIBRARY_PATH,PATH,PYTHONPATH,OMP_NUM_THREADS,CUDA_VISIBLE_DEVICES,RP_AGENT_ID,RP_GTOD,RP_PILOT_ID,RP_PILOT_STAGING,RP_PROF,RP_SESSION_ID,RP_SPAWNER_ID,RP_TMP,RP_UNIT_ID,RP_UNIT_NAME,CUDA_VISIBLE_DEVICES" /scratch/06079/tg853783/conda/w
f-2/bin/python "/scratch/06079/tg853783/git/DrugWorkflows/workflow-2/MD_exps/fs-pep/run_openmm.py" "--pdb_file" "/scratch/06079/tg853783/git/DrugWorkflows/workflow-2/MD_exps/fs-pep/pdb/100-fs-peptide-400K.pdb" "--length" "10"
```

I was expecting to see the training progress like::
```
 92/250 [=========>....................] - ETA: 1:36 - loss: 58656.8651
 92/250 [==========>...................] - ETA: 1:36 - loss: 58693.5760
 93/250 [==========>...................] - ETA: 1:35 - loss: 58635.0488
 93/250 [==========>...................] - ETA: 1:35 - loss: 58676.5983
 94/250 [==========>...................] - ETA: 1:33 - loss: 58595.5613
 94/250 [==========>...................] - ETA: 1:34 - loss: 58582.7384
 95/250 [==========>...................] - ETA: 1:33 - loss: 58634.4292
 95/250 [==========>...................] - ETA: 1:33 - loss: 58568.8768
 96/250 [==========>...................] - ETA: 1:32 - loss: 58615.4957
```
from the STDOUT but there was nothing generated.

**Comment by mtitov** [comment]
with MPI run command provided, I would think it is OpenMPI or MVAPICH2 software stack used, what was checked and confirmed working is Spectrum MPI software stack. Then I also removed `conda` activations inside the launching script, since env setup is done by bootstrap script, and it is supposed to use installed packages (and not re-intsall them). Latest update for Longhorn should clear it all up

**Comment by lee212** [comment]
As far as I remember, this has been resolved and stored the implementation with README in the separate branch: https://github.com/2019-ncovgroup/DrugWorkflows/tree/wf2/adrp/workflow-2
