### ISSUE TITLE
Workflow-4 Performance Issue

### ISSUE THREAD

**Issue by darkwhite29** [2019-ncovgroup/DrugWorkflows#21]
@apbhati1 Hi Agastya, I have been trying to improve the performance of workflow-4 based on your JSRUN Shell scripts. I created a README in workflow-4 directory. Regarding performance, I noticed you use "`+pemap`" and "`+commap`" in your scripts, which brings the following question which may need your clarification:

Are "+pemap" and "+commap" for performance enhancement purposes? How do they work, e.g., "`+pemap 0-83:4,88-171:4`", "`+commap 0,28,56,88,116,144`"? (I understand a bit but may still need your expertise)

The reason I am asking is that when transforming the scripts into RCT EnTK, we are not allowed to use those mapping -- RCT will do the mapping for the user. Using those mapping in RCT incurs CPU affinity errors. In order to get rid of all errors, I managed to remove those mapping in my EnTK script (as you can see in `workflow-4.py`) by carefulling setting resource requirements for EnTK tasks. However, now I am experiencing considerable slowdown (numbers not yet posted).

So just wanted to ask your opinion before I move to future steps. Thanks a lot for your help!

**Comment by apbhati1** [comment]
Hi @darkwhite29, Thank you for the update. 

`+pemap` and `+commap` are used for distributing processes between cores appropriately. Configuring this way indeed leads to performance enhancement as NAMD distributes available compute resources and memory between its tasks. A more detailed description of its usage is available at https://www.ks.uiuc.edu/Research/namd/2.13/ug/node105.html which should help you understand its usage better and adapt your code accordingly.

Hope this helps.

**Comment by darkwhite29** [comment]
Thanks Agastya @apbhati1 for the information. Do you have any thoughts based on my EnTK script? Andre @andre-merzky and Matteo @mturilli Thanks a lot!
